Feature/security analysis test cases creator
powsybl/powsybl-integration-test pull request #11
Opened 2022-11-17 13:41 UTC by tlec-artelys

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
- Added internal classes to provide contingencies and state monitors

**What is the current behavior?** *(You can also link to an open issue here)*
Files containing contingencies and state monitors are inputs to the creation of security analysis test cases.

**What is the new behavior (if this is a feature change)?**
Creates test cases for security analysis without specifying files for the contingencies or the state monitors.
The creation of new test cases generates the contingencies and state monitors files.

2022-11-18 17:03 UTC, armic-artelys requested changes
Il faut modifier des choses (voir mes commentaires)

2022-11-18 17:03 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/statemonitors/DefaultStateMonitorsProvider.java
> +    public List<StateMonitor> createStateMonitorList(Network network) {
Essaie de ne pas oublier les @Override (pas absolument nécessaires mais aide à la lecture)

2022-11-18 17:03 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/statemonitors/DefaultStateMonitorsProvider.java
> +        Iterable<Branch> branches = network.getBranches();
Ici aussi tu peux faire le tout en une seule ligne et réduire la taille générale de la méthode.
Ex:
```java
network.getVoltageLevels().forEach(vl -> voltageLevelIds.add(vl.getId()));
```

2022-11-22 17:02 UTC, armic-artelys reviewed
OK pour moi (à part un petit détail pas très important)
@obrix, je te laisse nous dire ce que tu en penses.

2022-11-22 17:17 UTC, armic-artelys requested changes
Toujours des problèmes dans la classe DefaultContingenciesProvider

2022-11-23 08:40 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/security/contingencies/DefaultContingenciesProvider.java
> +import org.jgrapht.alg.util.Pair;
If Pairs are really necessary the implementations from org.apache.commons.math3.util and org.apache.commons.lang3.tuple are used within powsybl-core. I think we should stick with the one of them (the on from lang package seems more used.

2022-11-23 08:43 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/security/contingencies/ContingenciesProvider.java
> +public interface ContingenciesProvider {
I think you can reuse ContingenciesProvider from powsybl-core that has the exact same prototype. If you absolutely want to use a different interface maybe name it differently.

2022-11-23 10:13 UTC, tlec-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/contingencies/ContingenciesProvider.java
> +public interface ContingenciesProvider {
I removed the interface I had created, and I reuse the one in contingency-api.
Thank you.

2022-11-23 10:14 UTC, tlec-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/SATestcaseCreator.java
> +        ObjectMapper mapperStateMonitors = JsonUtil.createObjectMapper();
Si tout à fait, merci.

2022-11-23 10:21 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/contingencies/DefaultContingenciesProvider.java
> +import org.jgrapht.alg.util.Pair;
I'm not against the use of Pairs, but rather against the use of a class that comes from a graph-related lib, while doing absolutely nothing graph-related here. We should not have an explicit dependency to jgrapht.

2022-11-24 14:56 UTC, armic-artelys approved these changes
OK pour moi

2022-11-24 14:58 UTC, merged