[WIP] Feature/security analysis
powsybl/powsybl-integration-test pull request #9
Opened 2022-10-24 12:23 UTC by armic-artelys

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
- Added internal classes to perform integration tests on SA.

**What is the current behavior?** *(You can also link to an open issue here)*
Only Loadflow tests can be performed.

**What is the new behavior (if this is a feature change)?**
No new behavior atm. Peripheral classes still need to be added.

**Other information**:
This is WIP. Do not merge for the moment !

2022-10-28 16:00 UTC, armic-artelys commented
@obrix : PR is now ready to be reviewed.

2022-11-03 14:46 UTC, obrix requested changes
First review : 
* StateMonitor configuration is missing from the SAComputationParameters leading to empty network results.
* To be coherent with LoadFlow API from the core I think all Loadflow* shoul actually by LoadFlow*
* Also to be coherent with the core and to avoid futur ambiguity with SensitivityAnalysis I think all SA* class should be called more explicitly SecurityAnalysis*

2022-11-03 14:46 UTC, obrix commented on src/test/resources/saTestPlan.json
> +      "expectedNetwork" : "sareferences/6noeuds_dummy.xiidm",
I think you lack a state monitor attribute to actually monitor network element at the pre / post contingency state (see 6noeuds_dummy.json networkResults are empty).

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationParameters.java
> +
List of StateMonitor to be added here probably.

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/loadflow/LoadflowTestcaseCreator.java
> +public class LoadflowTestcaseCreator {
I think it should be LoadFlowTestCaseCreator (see LoadFlow API in the core and TestCase here)

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/loadflow/LoadflowTestcaseCreatorParameters.java
> +class LoadflowTestcaseCreatorParameters {
LoadFlowTestCaseCreatorParameters

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/security/SATestcaseCreator.java
> +public class SATestcaseCreator {
SecurityAnalysisTestCaseCreator

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/creation/security/SATestcaseCreatorParameters.java
> +public class SATestcaseCreatorParameters {
SecurityAnalysisTestCaseCreatorParameters

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/loadflow/jsonconfig/LoadflowTestCaseJsonDeserializer.java
> +    public LoadflowTestCaseJson deserialize(JsonParser parser, DeserializationContext context) throws IOException {
LoadFlowTestCaseJson

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/loadflow/model/LoadflowComputationRunner.java
> +public class LoadflowComputationRunner implements ComputationRunner<LoadflowComputationParameters, LoadflowComputationResults> {
LoadFlowComputationRunner

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestCaseJson.java
> +public class SATestCaseJson {
SecurityAnalysisTestCaseJson

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestCaseJsonDeserializer.java
> +public class SATestCaseJsonDeserializer extends StdDeserializer<SATestCaseJson> {
SecurityAnalysisTestCaseJsonDeserializer

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanJson.java
> +public class SATestPlanJson {
SecurityAnalysisTestPlanJson

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanJsonDeserializer.java
> +public class SATestPlanJsonDeserializer extends StdDeserializer<SATestPlanJson> {
SecurityAnalysisTestPlanJsonDeserializer

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanReader.java
> +public class SATestPlanReader implements TestPlanReader<SAComputationParameters, SAComputationResults, SATestCase> {
SecurityAnalysisTestPlanReader

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationParameters.java
> +public class SAComputationParameters implements ComputationParameters {
SecurityAnalysisComputationParameters

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationResults.java
> +public class SAComputationResults implements ComputationResults {
SecurityAnalysisComputationResults

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationRunner.java
> +public class SAComputationRunner implements ComputationRunner<SAComputationParameters, SAComputationResults> {
SecurityAnalysisComputationRunner

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SATestCase.java
> +public class SATestCase implements TestCase<SAComputationParameters, SAComputationResults> {
SecurityAnalysisTestCase

2022-11-03 14:46 UTC, obrix commented on src/main/java/com/powsybl/integrationtest/security/model/SATestRunner.java
> +public class SATestRunner extends AbstractTestRunner<SAComputationParameters, SAComputationResults> {
SecurityAnalysisTestRunner

2022-11-04 11:49 UTC, armic-artelys commented on src/test/resources/saTestPlan.json
> +      "expectedNetwork" : "sareferences/6noeuds_dummy.xiidm",
My bad : added them.

2022-11-04 11:50 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationParameters.java
> +
true

2022-11-04 11:58 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/loadflow/LoadflowTestcaseCreator.java
> +public class LoadflowTestcaseCreator {
Fixed

2022-11-04 11:58 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/loadflow/LoadflowTestcaseCreatorParameters.java
> +class LoadflowTestcaseCreatorParameters {
Fixed

2022-11-04 12:13 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/SATestcaseCreator.java
> +public class SATestcaseCreator {
done

2022-11-04 12:13 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/creation/security/SATestcaseCreatorParameters.java
> +public class SATestcaseCreatorParameters {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/loadflow/jsonconfig/LoadflowTestCaseJsonDeserializer.java
> +    public LoadflowTestCaseJson deserialize(JsonParser parser, DeserializationContext context) throws IOException {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestCaseJson.java
> +public class SATestCaseJson {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanJson.java
> +public class SATestPlanJson {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanReader.java
> +public class SATestPlanReader implements TestPlanReader<SAComputationParameters, SAComputationResults, SATestCase> {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationResults.java
> +public class SAComputationResults implements ComputationResults {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationRunner.java
> +public class SAComputationRunner implements ComputationRunner<SAComputationParameters, SAComputationResults> {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SATestCase.java
> +public class SATestCase implements TestCase<SAComputationParameters, SAComputationResults> {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SATestRunner.java
> +public class SATestRunner extends AbstractTestRunner<SAComputationParameters, SAComputationResults> {
done

2022-11-04 12:14 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/jsonconfig/SATestPlanJsonDeserializer.java
> +public class SATestPlanJsonDeserializer extends StdDeserializer<SATestPlanJson> {
done

2022-11-04 12:15 UTC, armic-artelys commented on src/main/java/com/powsybl/integrationtest/security/model/SAComputationParameters.java
> +public class SAComputationParameters implements ComputationParameters {
done

2022-11-04 12:15 UTC, armic-artelys commented
I have done the changes : you can keep-on with the review.

2022-11-18 08:44 UTC, obrix approved these changes

2022-11-18 14:22 UTC, closed without merging